### ISSUE TITLE
Which Si5351 library?

### ISSUE THREAD

**Issue by Claudio-Sjo** [danak6jq/si5351-generic#2]
Hi Dana,
I was trying some libs from github for my new SDR project.
So far I tried NT7S and it didn't compile due to coding bugs, then I switched to your version of NT7S here https://github.com/danak6jq/Si5351 but also your code doesn't compile without correction. For instance in function si5351_set_multisynth there's a parameter passed as enum si5351_clock clock but then it's used as clk. It looks like the code has been stored before being fixed.
Is this si5351-generic library working? At least, does it compile?

Thanks,
Claudio

**Comment by danak6jq** [comment]
What error are you seeing exactly - I *think* 'clk' is undefined in si5351_set_multisynth() . It's been a long time since I looked at this code, I vaguely recall I pushed it here so Jason could integrate changes I'd made eliminating the use of floating-point in his repo and it was a work-in-progress at the time. As such, I'm not maintaining this repo, and I suspect Jason isn't maintaining the upstream repo.

I'd have a look at https://github.com/etherkit/Si5351Arduino for the actively-maintained Si5351 library from Jason; there's an mbed port of it at https://github.com/g7uvw/mbed_si5351
